### ISSUE TITLE
mirrors-help.osa.moe/github-raw not found

### ISSUE THREAD

**Issue by kowyo** [hitszosa/mirrors-frontend#11] opened 2024-03-26 08:48 UTC
**Describe the bug**

The [link](https://mirrors-help.osa.moe/github-raw/) in https://mirrors-help.osa.moe/rosdistro/ not found.

**To Reproduce**
1. Go to https://mirrors-help.osa.moe/rosdistro/
2. Click on [GitHub RAW 镜像](https://mirrors-help.osa.moe/github-raw/) 
3. See error

**Comment by rewired-gh** [comment] 2024-03-27 01:55
Thanks for your report. However, this issue is unrelated to this repository so I might close it now.

The repository for <https://mirrors-help.osa.moe> is <https://github.com/hitszosa/mirrorz-help> and you can open a new issue there. We will also try to synchronize with upstream and experiment with some workarounds to address this issue.

The root cause of the problem is any article should not cross-reference other articles, because it cannot assume whether an article is included by the configuration. I would highly suggest opening an issue in <https://github.com/mirrorz-org/mirrorz-help/issues>, since the root cause happens there.

**Closed by rewired-gh** 2024-03-27 01:55 UTC

**Comment by kowyo** [comment] 2024-03-27 07:04
Thank you for the quick reply! I would like to open a new issue. However, the repo mentioned above is not accessible too.

**Comment by rewired-gh** [comment] 2024-03-31 04:19
> Thank you for the quick reply! I would like to open a new issue. However, the repo mentioned above is not accessible too.

I'm sorry for the mistake. It is accessible now.

**Comment by rewired-gh** [comment] 2024-03-31 04:20
> Thank you for the quick reply! I would like to open a new issue. However, the repo mentioned above is not accessible too.

I'm sorry for the mistake. It is accessible now.
